<!DOCTYPE html>
<html>
<head>
    <meta HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=UTF-8"></meta>
    <title>AeBike API</title>
</head>

<body>
<div id="view-content">
    <ul>
        <li>
            <div>
                <div class="apiName">createuser</div>
                <div class="shortDesc">/*创建用户账号*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">createplan</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">getplanlist</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">getownplanlist</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">submitsummary</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">acceptplan</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
        <li>
            <div>
                <div class="apiName">startplan</div>
                <div class="shortDesc">/*创建计划*/</div>
                <div class="apiDesc">
                    <ul>
                        <li>username</li>
                        <li>password</li>
                        <li>name</li>
                        <li>emailaddress</li>
                    </ul>
                </div>
            </div>
        </li>
    </ul>
</div>
</body>

</html> 
